# job
run_tests:
    image: python:3.9-slim-buster
    # before
    before_script:
        - apt-get update && apt-get install make
        - pip install --upgrade Flask
        - pip install jinja2==2.11.3
        - python -c "import jinja2; print(jinja2.__version__)"
    # main 
    script:
        - make test
